spring:
  profiles: window
  datasource:
    base:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.244.2.3:3306/api3unlock?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://47.106.207.16:3306/guarantee?useUnicode=true&characterEncoding=UTF-8
      username: api3unlock
      password: Sci5XYpsFeFC4wEX

      max-idle: 20
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

server:
  port: 8023
chromedriverPath: C:\java\crawl\chromedriver.exe
daYangDistinguishPath: C:\java\crawl\crawl\DaYangDistinguish.dll
cacheDir: C:\java\crawl\cache\
enableProxy: true
proxyPath: D:\crawl\proxy.zip
codeUrl: http://47.75.138.140:8022/code/get_code
---

spring:
  profiles: linux
  datasource:
    base:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.244.2.3:3306/api3unlock?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&autoReconnect=true
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://47.106.207.16:3306/guarantee?useUnicode=true&characterEncoding=UTF-8
      username: api3unlock
      password: Sci5XYpsFeFC4wEX

      max-idle: 20
      min-idle: 20
      initial-size: 20
      max-wait: 10000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

server:
  port: 8023
chromedriverPath: /java/chromedriver
daYangDistinguishPath: /java/DaYangDistinguish.dll
cacheDir: /java/cache
enableProxy: true
proxyPath: /java/proxy.zip
codeUrl: http://47.75.138.140:8022/code/get_code
