spring:
  application:
    name: business-server

  # 分布式事务配置
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

order-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule