spring:
  application:
    name: business-server
server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

order-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule