server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false   #是否将自己注册到eureka
    fetch-registry: false         #是否拉取eireka服务注册表
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
